name: Setup Nix
description: Install Nix and configure Cachix

inputs:
  cachix-auth-token:
    description: Cachix auth token
    required: false

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ github.token }}

    - uses: cachix/cachix-action@v16
      with:
        name: ryo-morimoto
        authToken: ${{ inputs.cachix-auth-token }}
        skipPush: true
